name: Dress the Mannequins
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/e4316536-f320-47a9-906b-8604f0ace9c0.png
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/6c66e3fa-63ae-4c7d-b70f-da98e834c846.png
layout_spectrum: 0.22585630560819947
typography_spectrum: 0.683070852378269
opengraph:
  type: ''
  appId: ''
color:
  brandColors:
    - '#DC3522'
    - '#D9CB9E'
    - '#374140'
    - '#2A2C2B'
    - '#1E1E20'
  brandStrength: 0.29885077966311746
  lightness: 0.5114284313096183
  saturation: 0.750016658575456
  rhythmicContrast: 0.6696599346302984
title: We'll Dress the Mannequins
author:
  name: ''
  url: ''
  email: ''
content_rating:
  adult: false
